ALTER TABLE clients
ADD COLUMN status ENUM('active', 'inactive') DEFAULT 'active',
ADD COLUMN image VARCHAR(255),
ADD COLUMN createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
