CREATE TABLE ventes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  produit VARCHAR(255) NOT NULL,
  client VARCHAR(255) NOT NULL,
  quantite INT NOT NULL,
  prix_unitaire FLOAT NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP
);
