

































































































export default PieceDetailsModal;};  );    </Dialog>      </DialogActions>        </Typography>            : "Non disponible"}            ? new Date(piece.updatedAt).toLocaleDateString("fr-FR")          {piece.updatedAt          Dernière mise à jour :{" "}        <Typography variant="body2" color="text.secondary">      <DialogActions sx={{ p: 3, justifyContent: "space-between" }}>      </DialogContent>        </Grid>          </Grid>            </PremiumCard>              />                sx={{ fontWeight: 600, fontSize: 16 }}                color="secondary"                label={piece.categorie || "Non renseigné"}              <Chip              <Divider sx={{ mb: 2 }} />              </Typography>                Catégorie              <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>            <PremiumCard>          <Grid item xs={12} md={6}>          </Grid>            </PremiumCard>              />                sx={{ fontWeight: 600, fontSize: 16 }}                color="primary"                label={piece.fournisseur || "Non renseigné"}              <Chip              <Divider sx={{ mb: 2 }} />              </Typography>                Fournisseur              <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>            <PremiumCard>          <Grid item xs={12} md={6}>        <Grid container spacing={3}>      <DialogContent>      </PremiumDialogTitle>        </IconButton>          <Close />        <IconButton onClick={onClose} sx={{ color: "white" }}>        </Typography>          Détails de la Pièce        <Typography variant="h5" sx={{ fontWeight: 600 }}>      <PremiumDialogTitle>    >      }}        },          boxShadow: "0 20px 40px rgba(0,0,0,0.1)",          borderRadius: 3,        sx: {      PaperProps={{      fullWidth      maxWidth="md"      onClose={onClose}      open={open}    <Dialog  return (const PieceDetailsModal = ({ open, onClose, piece }) => {}));  border: "1px solid #e0e0e0",  borderRadius: theme.shape.borderRadius,  padding: theme.spacing(3),const PremiumCard = styled(Card)(({ theme }) => ({}));  padding: theme.spacing(3),  justifyContent: "space-between",  alignItems: "center",  display: "flex",  color: "white",  background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",const PremiumDialogTitle = styled(DialogTitle)(({ theme }) => ({import { styled } from "@mui/material/styles";import { Close } from "@mui/icons-material";} from "@mui/material";  Chip,  Divider,  Card,  Grid,  IconButton,  Typography,  DialogActions,  DialogContent,  DialogTitle,  Dialog,import {import React, { useState, useEffect } from "react";